### ISSUE TITLE
Including docs in this repo

### ISSUE THREAD

**Issue by joehand** [whoisgina/dat-foundation-website#124]
What was the trade offs here? And can we include the docs on this site.

**Comment by RangerMauve** [comment]
Including docs shouldn't be too hard since they're markdown documents.

Pointing the old docs to the new docs might be a bit of a pain, but it should be doable with redirect meta tags or something similar to make life easier for us.

**Comment by okdistribute** [comment]
I don't think we should do this because we don't have a ton of time and resources
