### ISSUE TITLE
Sponsors list

### ISSUE THREAD

**Issue by okdistribute** [whoisgina/dat-foundation-website#134]
I added sponsors to the about->foundation page, but they do not appear.

I suspect there is some html/css missing....

https://github.com/datproject/dat-foundation-website/commit/44bdc9bd7ca5be3e13bcb9c6e1d02a3186062555

@joehand @RangerMauve can someone jump on this? :)

**Comment by joehand** [comment]
See #141. 

I took out some of the html to expedite the launch for MOSS when there was missing/outdated content. If there is content missing, you should be able to find them on this branch https://github.com/datproject/dat-foundation-website/tree/all-content. You can [view the deployed](https://5df839e82136c50008221278--dat-foundation-next.netlify.com/) version of that branch too if you'd like to review what else we can add.

**Comment by okdistribute** [comment]
thanks @joehand
