### ISSUE TITLE
Blog post typo

### ISSUE THREAD

**Issue by decentral1se** [whoisgina/dat-foundation-website#152]
On https://blog.datproject.org/2019/12/18/moss-2019-summary/ there is a typo: "the reports from inidividual contributors.". I forked the project but then realised I can't edit the content from the posts because it is in Netlify? So, here is a ticket :)

**Comment by RangerMauve** [comment]
Thank you! I made the fix in the blog. We're going to eventually transition to have the blog on here, but sadly we haven't had time.
