### ISSUE TITLE
Specifying images for projects?

### ISSUE THREAD

**Issue by decentral1se** [whoisgina/dat-foundation-website#154]
I noticed that in the projects page, a featured image is passed with something like: "/images/field-notes.jpg", however when I cloned the site, I realised I can't edit or add images from there? Just wondering what is the flow for that.

**Comment by RangerMauve** [comment]
Could you elaborate on what issues you're having with adding images? You should be able to add them to the [images folder](https://github.com/datproject/dat-foundation-website/tree/release/site/.vuepress/public/images) and reference them from there.

**Comment by decentral1se** [comment]
Aha, I missed that directory! Thanks and sorry for the noise.

**Comment by RangerMauve** [comment]
No worries at all! It's good to see people's pain points when working with this stuff. It might be a good idea to update the README to make it more clear or something.
